enum Permission {
  dashboardRead,
  dossierRead,
  dossierCreate,
  dossierUpdate,
  dossierDelete,
  personneRead,
  documentRead,
  documentCreate,
  workflowRead,
  liquidationRead,
  rejetRead,
  importRead,
  engagementRead,
  archiveRead,
  notificationRead,
  administrationRead,
  auditRead,
  aiRead,
  settingsRead,
}

const Map<String, Permission> apiPermissionMap = {
  'dashboard.view': Permission.dashboardRead,
  'dossiers.view': Permission.dossierRead,
  'dossiers.create': Permission.dossierCreate,
  'dossiers.update': Permission.dossierUpdate,
  'dossiers.delete': Permission.dossierDelete,
  'personnes.view': Permission.personneRead,
  'documents.view': Permission.documentRead,
  'documents.create': Permission.documentCreate,
  'workflow.view': Permission.workflowRead,
  'liquidation.view': Permission.liquidationRead,
  'rejets.view': Permission.rejetRead,
  'imports.view': Permission.importRead,
  'engagements.view': Permission.engagementRead,
  'archives.view': Permission.archiveRead,
  'notifications.view': Permission.notificationRead,
  'administration.manage': Permission.administrationRead,
  'audit.view': Permission.auditRead,
  'ai.view': Permission.aiRead,
  'settings.view': Permission.settingsRead,
};

Permission? permissionFromApi(String code) => apiPermissionMap[code];
